### ISSUE TITLE
Consider supporting this being symlinked as "otp-md5"

### ISSUE THREAD

**Issue by rubys** [apache/infrastructure-otp#1]
I wrote a similar script (made simpler as there is a ruby-otp gem which does much of the heavy lifting.

I don't do the copy/paste step, so I'm stealing that.  But I do one thing that this script does not: I parse the challenges from the command line arguments.  So I currently copy/paste the challenge to the local terminal command line, and copy the response back to the ssh window.

Many Unix utilities alter their behavior based on the value of `os.path.basename(sys.argv[0])`.  Perhaps this script could do likewise?

**Comment by gstein** [comment]
Thanks for the suggestion. Implemented!
